name: Run tests

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: blacktop/ghidra
      env:
        GHIDRA_INSTALL_DIR: /ghidra
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        apt install gcc
        python -m pip install --upgrade pip
        pip install pyhidra
        pip install pytest
    - name: Run tests
      run: |
        mkdir res/out
        pytest src/tests/user_tests.py
